mv ./WiSim.aps wisim.aps
mv ./WiSim.cpp wisim.cpp
mv ./WiSim.h wisim.h
mv ./WiSim.log wisim.log
mv ./WiSim.pro.user wisim.pro.user
mv ./WiSim.rc wisim.rc
mv ./WiSim_cmdwin.log wisim_cmdwin.log
mv ./WiSim_gui.cpp wisim_gui.cpp
mv ./WiSim_gui.h wisim_gui.h
mv ./WiSim_zh.qm wisim_zh.qm
mv ./WiSim_zh.ts wisim_zh.ts
